server:
  port: 6001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
       # server-addr: localhost:8848 #配置Nacos地址
        server-addr: http://169.254.135.8:8989/

# 暴漏端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


