server:
  port: 8401

spring:
  application:
    name: cloudAlibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置Sentinel dashboard地址
        port: 8719
      datasource:
        # 流控规则
        flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            namespace: public
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-sentinel-flow-rules
            # 规则类型：flow、degrade、param-flow、system、authority
            rule-type: flow

#      datasource:
#        ds1:
#          nacos:
#            server-addr: localhost:8848 # Nacos服务注册中心地址
#            dataId: cloudalibaba-sentinel-service # 应用服务名字
#            groupId: DEFAULT_GROUP # 分组id
#            data-type: json # 数据类型
#            rule-type: flow # 规则类型 flow是限流


management:
  endpoints:
    web:
      exposure:
        include: '*'


